language: python
matrix:
  include:
    # unittesting 2.7 - 3.6
    - python: 2.7
      env:
        JOB_NAME=unittest
        TOXENV=py27
    - python: 3.5
      env:
        JOB_NAME=unittest
        TOXENV=py35
    - python: 3.6
      env:
        JOB_NAME=unittest
        TOXENV=py36
    # stylish checks
    - env:
        JOB_NAME=pep8
        TOXENV=pep8
    # run real rally task
    - python: 3.5
      env:
        JOB_NAME="Rally Task"
        TOXENV=run-task
        XRALLY_TASK="./tasks/all-in-one.json"
      services:
        - docker
script:
  - tox
install:
  - pip install tox
